# Generated by Django 2.0.5 on 2018-05-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCorp',
            fields=[
                ('org', models.IntegerField(db_column='ORG', primary_key=True, serialize=False)),
                ('id', models.IntegerField(db_column='ID')),
                ('seq_id', models.IntegerField(db_column='SEQ_ID')),
                ('reg_no', models.CharField(blank=True, db_column='REG_NO', max_length=255, null=True)),
                ('corp_name', models.CharField(blank=True, db_column='CORP_NAME', max_length=255, null=True)),
                ('addr', models.CharField(blank=True, db_column='ADDR', max_length=255, null=True)),
                ('belong_dist_org', models.CharField(blank=True, db_column='BELONG_DIST_ORG', max_length=255, null=True)),
                ('belong_trade', models.CharField(blank=True, db_column='BELONG_TRADE', max_length=255, null=True)),
                ('econ_kind', models.CharField(blank=True, db_column='ECON_KIND', max_length=255, null=True)),
                ('admit_main', models.CharField(blank=True, db_column='ADMIT_MAIN', max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, db_column='START_DATE', null=True)),
                ('check_date', models.DateField(blank=True, db_column='CHECK_DATE', null=True)),
                ('open_man_ident_no', models.CharField(blank=True, db_column='OPEN_MAN_IDENT_NO', max_length=255, null=True)),
                ('open_man_name', models.CharField(blank=True, db_column='OPEN_MAN_NAME', max_length=255, null=True)),
                ('corp_status', models.CharField(blank=True, db_column='CORP_STATUS', max_length=255, null=True)),
                ('reg_capi', models.FloatField(blank=True, db_column='REG_CAPI', null=True)),
                ('fare_team_start', models.DateField(blank=True, db_column='FARE_TEAM_START', null=True)),
                ('fare_team_end', models.CharField(blank=True, db_column='FARE_TEAM_END', max_length=255, null=True)),
                ('fare_scope', models.TextField(blank=True, db_column='FARE_SCOPE', null=True)),
                ('uni_scid', models.CharField(blank=True, db_column='UNI_SCID', max_length=255, null=True)),
                ('tel', models.CharField(blank=True, db_column='TEL', max_length=255, null=True)),
                ('web_url', models.CharField(blank=True, db_column='WEB_URL', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=255, null=True)),
                ('prac_person_num', models.IntegerField(blank=True, db_column='PRAC_PERSON_NUM', null=True)),
                ('org_inst_code', models.CharField(blank=True, db_column='ORG_INST_CODE', max_length=255, null=True)),
                ('taxpay_num', models.CharField(blank=True, db_column='TAXPAY_NUM', max_length=255, null=True)),
                ('staff_size', models.CharField(blank=True, db_column='STAFF_SIZE', max_length=255, null=True)),
                ('english_name', models.CharField(blank=True, db_column='ENGLISH_NAME', max_length=255, null=True)),
                ('former_name', models.CharField(blank=True, db_column='FORMER_NAME', max_length=255, null=True)),
                ('create_date', models.DateTimeField(blank=True, db_column='CREATE_DATE', null=True)),
                ('create_org', models.IntegerField(blank=True, db_column='CREATE_ORG', null=True)),
            ],
            options={
                'db_table': 't_corp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TCorpDist',
            fields=[
                ('org', models.IntegerField(db_column='ORG', primary_key=True, serialize=False)),
                ('id', models.IntegerField(db_column='ID')),
                ('seq_id', models.IntegerField(db_column='SEQ_ID')),
                ('dist_reg_no', models.CharField(blank=True, db_column='DIST_REG_NO', max_length=255, null=True)),
                ('dist_name', models.CharField(blank=True, db_column='DIST_NAME', max_length=255, null=True)),
                ('dist_belong_org', models.CharField(blank=True, db_column='DIST_BELONG_ORG', max_length=255, null=True)),
                ('dist_corp_org', models.IntegerField(blank=True, db_column='DIST_CORP_ORG', null=True)),
                ('dist_corp_id', models.IntegerField(blank=True, db_column='DIST_CORP_ID', null=True)),
                ('dist_corp_seq_id', models.IntegerField(blank=True, db_column='DIST_CORP_SEQ_ID', null=True)),
                ('fare_place', models.CharField(blank=True, db_column='FARE_PLACE', max_length=255, null=True)),
                ('oper_man_ident_no', models.CharField(blank=True, db_column='OPER_MAN_IDENT_NO', max_length=255, null=True)),
                ('oper_man_name', models.CharField(blank=True, db_column='OPER_MAN_NAME', max_length=255, null=True)),
                ('fare_scope', models.CharField(blank=True, db_column='FARE_SCOPE', max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, db_column='START_DATE', null=True)),
                ('check_date', models.DateField(blank=True, db_column='CHECK_DATE', null=True)),
                ('create_date', models.DateTimeField(blank=True, db_column='CREATE_DATE', null=True)),
            ],
            options={
                'db_table': 't_corp_dist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TCorpPertains',
            fields=[
                ('org', models.IntegerField(db_column='ORG', primary_key=True, serialize=False)),
                ('id', models.IntegerField(db_column='ID')),
                ('seq_id', models.IntegerField(db_column='SEQ_ID')),
                ('certificate_type', models.CharField(blank=True, db_column='CERTIFICATE_TYPE', max_length=255, null=True)),
                ('person_name', models.CharField(blank=True, db_column='PERSON_NAME', max_length=255, null=True)),
                ('person_type', models.CharField(blank=True, db_column='PERSON_TYPE', max_length=255, null=True)),
                ('certificate_no', models.CharField(blank=True, db_column='CERTIFICATE_NO', max_length=255, null=True)),
                ('select_type', models.CharField(blank=True, db_column='SELECT_TYPE', max_length=255, null=True)),
                ('holdpost_start', models.DateField(blank=True, db_column='HOLDPOST_START', null=True)),
                ('holdpost_edn', models.DateField(blank=True, db_column='HOLDPOST_EDN', null=True)),
                ('sex', models.CharField(blank=True, db_column='SEX', max_length=255, null=True)),
                ('age', models.CharField(blank=True, db_column='AGE', max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_column='COUNTRY', max_length=255, null=True)),
                ('create_date', models.DateTimeField(blank=True, db_column='CREATE_DATE', null=True)),
            ],
            options={
                'db_table': 't_corp_pertains',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TCorpStock',
            fields=[
                ('org', models.IntegerField(db_column='ORG', primary_key=True, serialize=False)),
                ('id', models.IntegerField(db_column='ID')),
                ('sed_id', models.IntegerField(db_column='SED_ID')),
                ('stock_type', models.CharField(blank=True, db_column='STOCK_TYPE', max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_column='COUNTRY', max_length=255, null=True)),
                ('certificate_type', models.CharField(blank=True, db_column='CERTIFICATE_TYPE', max_length=255, null=True)),
                ('certificate_no', models.CharField(blank=True, db_column='CERTIFICATE_NO', max_length=255, null=True)),
                ('stock_name', models.CharField(blank=True, db_column='STOCK_NAME', max_length=255, null=True)),
                ('stock_capi_type', models.IntegerField(blank=True, db_column='STOCK_CAPI_TYPE', null=True)),
                ('stock_capi', models.FloatField(blank=True, db_column='STOCK_CAPI', null=True)),
                ('stock_capi_dollar', models.IntegerField(blank=True, db_column='STOCK_CAPI_DOLLAR', null=True)),
                ('stock_capi_rmb', models.IntegerField(blank=True, db_column='STOCK_CAPI_RMB', null=True)),
                ('stock_percent', models.CharField(blank=True, db_column='STOCK_PERCENT', max_length=255, null=True)),
                ('stock_rate_rmb', models.IntegerField(blank=True, db_column='STOCK_RATE_RMB', null=True)),
                ('stock_rate_dollar', models.IntegerField(blank=True, db_column='STOCK_RATE_DOLLAR', null=True)),
                ('create_date', models.DateTimeField(blank=True, db_column='CREATE_DATE', null=True)),
            ],
            options={
                'db_table': 't_corp_stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TMCorpCorpDist',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('seq_id', models.IntegerField(db_column='SEQ_ID')),
                ('org', models.IntegerField(db_column='ORG')),
                ('sub_org', models.IntegerField(db_column='SUB_ORG')),
                ('sub_id', models.IntegerField(db_column='SUB_ID')),
                ('sub_seq_id', models.IntegerField(db_column='SUB_SEQ_ID')),
            ],
            options={
                'db_table': 't_m_corp_corp_dist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TMCorpCorpPertains',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('seq_id', models.IntegerField(db_column='SEQ_ID')),
                ('org', models.IntegerField(db_column='ORG')),
                ('sub_org', models.IntegerField(db_column='SUB_ORG')),
                ('sub_id', models.IntegerField(db_column='SUB_ID')),
                ('sub_seq_id', models.IntegerField(db_column='SUB_SEQ_ID')),
            ],
            options={
                'db_table': 't_m_corp_corp_pertains',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TMCorpCorpStock',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('seq_id', models.IntegerField(db_column='SEQ_ID')),
                ('org', models.IntegerField(db_column='ORG')),
                ('sub_org', models.IntegerField(db_column='SUB_ORG')),
                ('sub_id', models.IntegerField(db_column='SUB_ID')),
                ('sub_seq_id', models.IntegerField(db_column='SUB_SEQ_ID')),
            ],
            options={
                'db_table': 't_m_corp_corp_stock',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='tmcorpcorpstock',
            unique_together={('id', 'seq_id', 'org', 'sub_org', 'sub_id', 'sub_seq_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tmcorpcorppertains',
            unique_together={('id', 'seq_id', 'org', 'sub_org', 'sub_id', 'sub_seq_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tmcorpcorpdist',
            unique_together={('id', 'seq_id', 'org', 'sub_org', 'sub_id', 'sub_seq_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tcorpstock',
            unique_together={('org', 'id', 'sed_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tcorppertains',
            unique_together={('org', 'id', 'seq_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tcorpdist',
            unique_together={('org', 'id', 'seq_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tcorp',
            unique_together={('org', 'id', 'seq_id')},
        ),
    ]
